# default application setting
# encoding properties
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

# spring properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://miraero.mysql.database.azure.com/mirae?serverTimezone=UTC&characterEncoding=UTF-8
    username: miraero
    password: Alfofh!1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true